### ISSUE TITLE
描述字段descr不显示文字

### ISSUE THREAD

**Issue by bxplosion** [lijiabao9/hexo-butterfly-categories-card-gabriel#1]
```
# hexo-butterfly-categories-card-gabriel
# see https://github.com/lijiabao9/hexo-butterfly-categories-card-gabriel
categoryBar:
  enable: true    # 开关
  priority: 5     # 过滤器优先权
  enable_page: /  # 应用页面
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  column: odd     # odd：3列 | even：4列
  row: 1          # 显示行数，默认两行，超过行数切换为滚动显示
  message:
    - name: 前端开发
      descr: 前端方面的技术记录学习
      cover: https://cdn.jsdelivr.net/gh/lijiabao9/lijiabao9.pic.cloud@main/PicGo/202404162145545.png
    - name: 后端开发
    - descr: 后端方面的技术记录学习
      cover: https://cdn.jsdelivr.net/gh/lijiabao9/lijiabao9.pic.cloud@main/PicGo/202404162144144.png
  custom_css: https://cdn.jsdelivr.net/npm/hexo-butterfly-categories-card-gabriel/lib/categorybar.css
```
demo第二个descr字段前面不能加横线，否则描述文字就丢失了，应该是与分组有关？
感谢功能补全❤
